---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-gatus-ep

  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: jellyfin
        group: "Web - Internal"
        url: https://jellyfin.prymal.info/web/index.html
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://10.10.1.31:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
