---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-hd-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: sonarr-hd
        group: "Web - Internal"
        url: https://sonarr-hd.prymal.info
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://10.10.1.31:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
