---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-webhooks
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/flux-system/addons/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
