ansible_become_pass: ENC[AES256_GCM,data:BUSaB4rDH+xTRpFn,iv:EDNalqYmf17q86fF+2CcOapC7bBGsTRPgYhqG7ZUl3U=,tag:2j2TQP0h9Q20+vcb2aaumQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d1VuYnhvMGxTcG82YWhY
            Y2R1Rk1RR0xVeElzeUhOVEk3NWlmTmVEMXhvCkxsNXZBeFFHbEZURWpJVHl4Y3ZN
            eGtDcVVZSE00VGZCS3hzU0NzanYwRUUKLS0tIGlkcUh6L2toVUtaVVBhWmFwY3pI
            U014eGtBUElBSWg5V2hnVHBXdnpJSGMKx9USCtcye4lFAmnCTVctNI3M4IasUmOK
            +A3PERzAgQ2XsXit3xTBmPz+u2SKGcqAU5q+thVzud7Lezn6PXU9aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-08T19:09:01Z"
    mac: ENC[AES256_GCM,data:2ZR8osuFvV9U5qKd2+io1L5Cj53gz7ZXr8pocKaXSpdNcK/kQrXL+ppX7AY9DJToxIAmdJo31xcwlYhwqrnDvdJicWjBBt0Ph1gdaqi1fxmAysjteAWK/pHbX7W1prGlJT7Nva+P53Pyam04bU5zhinLyrddrUxzF2CGBbl8WoY=,iv:bMHRGXmRGG2v2esb5hy08yqIBah5fIqpPln3BMbZFmk=,tag:cGrDFVnU7xznbh4HyfKtwQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
