ansible_become_pass: ENC[AES256_GCM,data:3qBNxnxZ7NprFzM7,iv:mptsgYiBVrEgUIxhLe+VuIdQVYcerGTT86WYv1uJ0/U=,tag:PQjzDpfhCB/72uWru8uyBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMkpkSWRVeURsWU1zOUtH
            dTM3b0RuTG9qMWZVNnBzOXlCRlNiYjlxMGhVClhkNzcvT081cm5QSWJYd3ZENTlX
            amQyQy9ja0dDNkNsYlpHQkcxVDNIazQKLS0tIGw0U1VmV3llWGVlWGJQTmc2akpj
            bjR4eDBHVHo4Tm1IYm5FQTk2dVN6MG8KTeV5AYGABbeHv9lXluiS7Mj0TSRYD00M
            uMeymjgMPaRCqSjW8zuNTl88uzBk8xs8yjPTzl01H1YgpPHXiSMYrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-08T18:04:50Z"
    mac: ENC[AES256_GCM,data:jd6NzZMbcxclPw6lEPlIQBp5jnpKQnEVMsK2T+u2vfJ4+GspStQWG8EzLgBXtOcpwMsXnVIkImObOdMzlRjx838UqmfcHIfJTwuApezWbO1JzrkjorycQrpq1QHWneTGmhMP/FxZ76VLYHbeAKwCQ8e+Pqx5DDXlV3w8Pjky0Xk=,iv:8x2VrXiQAMu5aFzwvd96r6f87nMZGr9cV6GS6AG0HUo=,tag:k0SoQ12AIag9VWnBzdeicA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
