ansible_become_pass: ENC[AES256_GCM,data:Bn2z02GWsGlfdAPA,iv:9ON6K3SazxVA+IMo5pzor0Nqac9kgKj66vvBg7+X4fY=,tag:uxD4nqb6S/5wupVUjqH9UQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWnJkSHBpZmdkbDBiT3hW
            MUQxSndRTW1WUDVEQnRlcjF1d3dNRmF5bjNNCmF4a1BxaWxjRWU4VVNGOU5pSnRo
            L01kWDM1TUlXRzF3VHpHY2NTOEEwR3cKLS0tICswRWhLR0gySXVQM0tDS3Z4MXpY
            RnN6RzJva3IyRWZnQkFSc3N6UVkzWjQK6TQ7xg2vI/sm740MhC7CtXWUWYRtUgxJ
            u0fB+YudwKPVQXlAGpZxCQ2eWHs94Tm/b50t048qdkrAbX1nZyxHGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-08T19:09:01Z"
    mac: ENC[AES256_GCM,data:m/UTjuMzY8XK0J3HBOmXQkMZi3WKJOtjirFmugHQdwKNRrZuJZzFoO3a9pGeIclc3trKOihTAFvV+T0VMr3zBpuuoZ8gE+fj42UGU4afb0JJqkIjTaFsXjL8AW9+kOf6wDAEw3XWXgtS0cu2CEQ+Es8B0C+nZYw3n/x0k+96bBI=,iv:3JCvMie2ONR5UznL3ArkVweC2qU9yhh6rAImT6ZWy8E=,tag:n6GXPW7Njkik8w14228wXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
