---
originRequest:
  http2Origin: true

ingress:
  - hostname: "prymal.info"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.prymal.info"
  - hostname: "*.prymal.info"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.prymal.info"
  - service: http_status:404
