---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./externalsecret.yaml
  - ./gatus.yaml
  - ./helmrelease.yaml
  - ./dashboard
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/instance: grafana
