apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Q+L/hxQS0T7Qk4ErbqFmL8jDicjqHKXu,iv:Z/FVPuSwxOmPQSywzSlvSur4FAWXcD4AMM9EZ6SzGSk=,tag:eweCWSHp1Bw/xR7j76GbJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVnZySlFFdTVlWGRNSnV6
            UVpPWThtVnduaWFIVkQxb3JBdXNIOXZyOTBvCkxCK2l2ZG9XRFRSMysvUEpEN25R
            RzVhZkxsekczUHZHVmF6SE5hRzJBMmMKLS0tIEwzTHpvcDJEM1B2SFF3em5jRnpW
            dUJaZWI2L3gwSVpDaWM1aWlYa01hZzAKYc0M1y4sBEi+FYZcJ8WEz1/FsMeb+4mk
            DcOfFmq3EY4gUmaoS+p4YyvsUwxB9Pxc354Y4b60qGeLFoQKiVpXNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-08T18:05:46Z"
    mac: ENC[AES256_GCM,data:40cCmSFD0RFI0v5MoYFmK7kmhOsNdzVqx/BhcLurZ440cfTBNo2VHuxQ6RAvaYqXaMlrl0NCwf2Lbx2NRZ5V4pwrjVyGbzHu94sDVAmDkLPG+k5kTk34aSnGpA6U7Y8A4q5wDaYC+U5KiNfTgfxziwNiirFb1uwwiH1z1DsJMUM=,iv:HxcUA+S/UziRcWRo1Fa+eX5ESupjQBYHUDwBPo0ousY=,tag:NmG/C5nj+7jV2qKk8bSaaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
