---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-gatus-ep

  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: minecraft
        group: "Games"
        url: tcp://10.10.1.104:25565
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
            failure-threshold: 5
            success-threshold: 2
            send-on-resolved: true
