apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:h0y62Z4sPSxXtd1Le1YcXHeChtTVAppCUNV10yqYWktSv9k4exkiFw==,iv:llpxkqlfiF1ahWhSOYXUVvUKEtu8mHgY+3j+ncyN0gI=,tag:ILQnfAQWRMptL8LazfILqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRjd0NzZBWGFqTmxqVVNq
            SHpER0tiM1l5czFaZUtGTVBNMXNLUy9kOUFRCmpWdDJOdGFOVnN6dVJVMFZYVG15
            Y1RjVHpMQkxZYStZYXpwdWlSYldLd00KLS0tIFBvRm8rc0YxSXhpN2dZbVBrSnJQ
            MGIwUlZqS2xZYW8yOXlwUHU5TUdHNW8Kov34hE3dmdEc3h7YnV2U2hwgY/XhCBWf
            WlAixBmysrQmi45msX0lvakvaNrVT6EM3691yKFrWDfpqRtditJucw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-08T19:09:58Z"
    mac: ENC[AES256_GCM,data:QV5ctEqdNrkC8WIhvkYQ0orb2OF57gyncNJy9rWNmbfDMAXqAy/2Xgpe+f8eoyuQvbyk4k6MSmzeCNiH0LPXcuVyb1Ce1TwJG7wYvfk5Z9WG4f0xfGaUMhlX1xcvakpHPxMi7YhPVj5V/LIwuyR4pPVS2iwUqrBPmXgGuhD9fMc=,iv:wdHWrtR/go4ZGFcP8uLrsAgys+rjJsKcSYmV2GY9ehE=,tag:Zo3tC6serrVrEt4XLWI+dA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
