---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-block
