---
apiVersion: v1
kind: Service
metadata:
  name: indexer
  namespace: wazuh
  labels:
    app: wazuh-indexer
    external-dns.alpha.kubernetes.io/hostname: wazuh-indexer.prymal.info
    io.cilium/lb-ipam-ips: 10.10.1.109
spec:
  type: LoadBalancer
  selector:
    app: wazuh-indexer
  ports:
    - name: indexer-rest
      port: 9200
      targetPort: 9200
