apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/oejgvm+WPV5bWIcROG1cHT/eUc=,iv:01f4UzPKWLYS5bBu5vf6awQzaxem+Y6YNUWihetsdhY=,tag:OW1XfZiylI4xMIJWj3DPOg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:n9nW8XkWd96r2QbI10ca0S+eBQ/tT8v6wc3pP2Kjk6qVLa5f,iv:PmhMGIrvk2hpxB1vqkdOYcIQbPq2QGLfKOP0XMvJZLo=,tag:TDfF1ip1fEmPDv2xaw2yyw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:huFX6qvkCJnz/vQ=,iv:WbJBrtzVlgPtZrSo69A7WZDGU2+fdtfWobtqvKoS5+c=,tag:A+FIC8xOcVTVB/XiFte2pw==,type:str]
    SECRET_PROMETHEUS_DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:qc5rez9/LXH0oA3sRsJVyRqAR5qLwDofvBQqbpCUqYinFuLT3XN5lCGTDfuctFxVWShCLSeXGlY9UZAPVGOj0vUXPhtNm1sCzmTe5B1I6Ji68RoYXQud3jMNJmf3DY30WFMc1f+Z81ag8r/Ppd1F6QC1jpmkhEb9mOqQ,iv:bB/XpPGqnSjDMJPde6UFPrIaT4Uxa0bXijIa1ubNka0=,tag:0oMqqBVoFIwGzMYZs7htVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y0VPZGs0MnVCbjYvMTVS
            azVyRWpCK05kUWUzRmtjTDIxSzZnekxxZ3ljCmkzTmE3QkhlUnBxcHNTUVh2Z0F0
            c1JPaU50d1lZN2hYYVVpcEVSVm1VRmMKLS0tIFZMM2NMNWtCdXlIQWJoUEpQZ1Ni
            S1ZseFluVG9TK2liZkZ4Yk5td2JEcUUK6ytOz+7nueMi5m3pGMro3G5O+xQyYFip
            e9fTyV7lM6EvzL3gvjeesopfCofoq0JQdQUyjAMJjSS7lCWw1K+Uwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T02:03:28Z"
    mac: ENC[AES256_GCM,data:WQOBF1a8xjknpNxcnrSKYR5Qe8DHjmGKl7JDxxACPV07IBnJ8C+AOWDT+A12qmU085uCE/PzATm11sbPXElesh4w8rJgo51fA31fkPElshvGj1bZJRDkoGdVdp8w5ZjPt16cc/c0wZghW6NPhdHdHiH1adMzZD1Yr7eXQ3jUE34=,iv:jcub3WVb5hD41phTNTSIM8b1iBni96rGBKvsMuBCVQo=,tag:K1p/KnRZHKVzCmqGt7Rbew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
