apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/oejgvm+WPV5bWIcROG1cHT/eUc=,iv:01f4UzPKWLYS5bBu5vf6awQzaxem+Y6YNUWihetsdhY=,tag:OW1XfZiylI4xMIJWj3DPOg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:n9nW8XkWd96r2QbI10ca0S+eBQ/tT8v6wc3pP2Kjk6qVLa5f,iv:PmhMGIrvk2hpxB1vqkdOYcIQbPq2QGLfKOP0XMvJZLo=,tag:TDfF1ip1fEmPDv2xaw2yyw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:huFX6qvkCJnz/vQ=,iv:WbJBrtzVlgPtZrSo69A7WZDGU2+fdtfWobtqvKoS5+c=,tag:A+FIC8xOcVTVB/XiFte2pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y0VPZGs0MnVCbjYvMTVS
            azVyRWpCK05kUWUzRmtjTDIxSzZnekxxZ3ljCmkzTmE3QkhlUnBxcHNTUVh2Z0F0
            c1JPaU50d1lZN2hYYVVpcEVSVm1VRmMKLS0tIFZMM2NMNWtCdXlIQWJoUEpQZ1Ni
            S1ZseFluVG9TK2liZkZ4Yk5td2JEcUUK6ytOz+7nueMi5m3pGMro3G5O+xQyYFip
            e9fTyV7lM6EvzL3gvjeesopfCofoq0JQdQUyjAMJjSS7lCWw1K+Uwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-08T19:09:59Z"
    mac: ENC[AES256_GCM,data:ONyzqH54sVxrHwhvwAjJ2fPXhdDNmh82kiPbffREKnKa8Qt/33WUL+F9+8NAHcUwfvA4DIKTToCCNyxDygmN1oy4ZVpdReWrH/Ll0HVqsHfSn0y4oDqbuDhuKYK2It0hy7dQh16jw5tMo7bifBoWD0qrvSJTTc6/jGRoeM0I0co=,iv:Q/S77kGNdDwY6t0hrT4haSMwi9J0wjGgn9hP0w2Iqsw=,tag:/sb+BG79bKUZbfxjPwp0pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
