---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: wazuh
  labels:
    app: wazuh-manager
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wazuh-worker.prymal.info
    io.cilium/lb-ipam-ips: 10.10.1.107
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: agents-events
      port: 1514
      targetPort: 1514
