---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: loki
        S3_BUCKET_HOST: scorpion.prymal.linux:9000
        S3_BUCKET_REGION: us-east-1
        S3_ACCESS_KEY: "{{ .access_key }}"
        S3_SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: loki
