---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: amd-gpu
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: amd-gpu-helm
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    nfd:
      enabled: true
    labeller:
      enabled: false
    namespace: kube-system
    dp:
      image:
        repository: docker.io/rocm/k8s-device-plugin
        # Overrides the image tag whose default is the chart appVersion.
        tag: "1.25.2.5"
      resources: {}
    lbl:
      image:
        repository: docker.io/rocm/k8s-device-plugin
        tag: "labeller-1.25.2.5"
      resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    node_selector:
      amd.feature.node.kubernetes.io/gpu: true
      kubernetes.io/arch: amd64
