---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dashboard-cred
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dashboard-cred
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: wazuh-dashboard
        property: USERNAME
    - secretKey: password
      remoteRef:
        key: wazuh-dashboard
        property: PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: indexer-cred
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: indexer-cred
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: wazuh-indexer
        property: USERNAME
    - secretKey: password
      remoteRef:
        key: wazuh-indexer
        property: PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wazuh-api-cred
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: wazuh-api
        property: USERNAME
    - secretKey: password
      remoteRef:
        key: wazuh-api
        property: PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-authd-pass
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wazuh-authd-pass
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: authd.pass
      remoteRef:
        key: wazuh-authd
        property: AUTHD_PASS
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-cluster-key
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wazuh-cluster-key
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: key
      remoteRef:
        key: wazuh-cluster-key
        property: CLUSTER_KEY
