---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dashboard-cred
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dashboard-cred
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: wazuh-dashboard
        property: USERNAME
    - secretKey: password
      remoteRef:
        key: wazuh-dashboard
        property: PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: indexer-cred
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: indexer-cred
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: wazuh-indexer
        property: USERNAME
    - secretKey: password
      remoteRef:
        key: wazuh-indexer
        property: PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wazuh-api-cred
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: wazuh-api
        property: USERNAME
    - secretKey: password
      remoteRef:
        key: wazuh-api
        property: PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-authd-pass
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wazuh-authd-pass
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: authd.pass
      remoteRef:
        key: wazuh-authd
        property: AUTHD_PASS
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-cluster-key
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wazuh-cluster-key
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: key
      remoteRef:
        key: wazuh-cluster-key
        property: CLUSTER_KEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dashboard-certs
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dashboard-certs
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        root-ca.pem: |
          {{ .ROOT_CA }}
        cert.pem: |
          {{ .DASHBOARD_CERT }}
        key.pem: |
          {{ .DASHBOARD_KEY }}
  dataFrom:
    - extract:
        key: wazuh-dashboard-certs
---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: indexer-certs
  namespace: wazuh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: indexer-certs
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        root-ca.pem: |
          {{ .root-ca.pem }}
        node.pem: |
          {{ .NODE_CERT }}
        node-key.pem: |
          {{ .NODE_KEY }}
        dashboard.pem: |
          {{ .DASHBOARD_CERT }}
        dashboard-key.pem: |
          {{ .DASHBOARD_KEY }}
        admin.pem: |
          {{ .ADMIN_CERT }}
        admin-key.pem: |
          {{ .ADMIN_KEY }}
        filebeat.pem: |
          {{ .FILEBEAT_CERT }}
        filebeat-key.pem: |
          {{ .FILEBEAT_KEY }}
  dataFrom:
    - extract:
        key: wazuh-indexer-certs
